// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace EscribeNumerosML.Model
{
    public class ModelInput
    {
        [ColumnName("numero"), LoadColumn(0)]
        public float Numero { get; set; }


        [ColumnName("letras"), LoadColumn(1)]
        public string Letras { get; set; }


    }
}
